---
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
library(dplyr)
library(flexdashboard)
library(readxl)
library(readr)
library(shiny)
library(rmarkdown)
library(knitr)
library(DT)
library(ggplot2)
library(ggthemes)
library(tidyr)
library(shinythemes)
library(data.table)
library(forecast)

assignInNamespace("cedta.override", c(data.table:::cedta.override,"rmarkdown"), "data.table")

opts_chunk$set(echo = FALSE, comment="", warning = FALSE, message = FALSE, tidy.opts=list(width.cutoff=55), tidy = TRUE)

```

```{r}
visits.national <- fread("https://raw.githubusercontent.com/Victoriaxyan/machine-churning/master/Data/flu_view_line(Topright%20%20Chart)_national.csv")

visits.state <- fread("https://raw.githubusercontent.com/Victoriaxyan/machine-churning/master/Data/State_Data/ILINet.csv")

flutype.national <- fread("https://raw.githubusercontent.com/Victoriaxyan/machine-churning/master/Data/National_Positive_tests_type.csv")

flutype.state <- fread("https://raw.githubusercontent.com/Victoriaxyan/machine-churning/master/Data/State_Data/WHO_NREVSS_Public_Health_Labs.csv",skip=1)

vaccine.national <- fread("https://raw.githubusercontent.com/Victoriaxyan/machine-churning/master/Data/usa_vaccination_data.csv")
```

```{r}
region.names <- c("national", unique(visits.state[,REGION]))
age.groups <- names(visits.national)[c(4:6,8:9)]
pred.length <- 4:52 #number of weeks want to plan ahead
datatype <- c("Visit Rates for ILI", 
              names(flutype.national)[c(7,9,10,12,13)],
              age.groups)


#date format change
visits.national[,MONTH:=lubridate::month(as.Date(paste0(YEAR, "-", 
                                                        WEEK, "-", 10), 
                                                 format = "%Y-%U-%u"))]
visits.national[,date:=as.Date(paste(YEAR,MONTH,1,sep="-"))]
visits.state[,MONTH:=lubridate::month(as.Date(paste0(YEAR, "-",WEEK, "-", 10),
                                              format = "%Y-%U-%u"))]
visits.state[,date:=as.Date(paste(YEAR,MONTH,1,sep="-"))]
flutype.national[,date:=as.Date(date)]
``` 

Modeling and Predictions
=====================================  
Row {data-height=500}
-------------------------------------
```{r modeling}

inputPanel(
  #select region
  selectInput(inputId= "Region", label = "Select Region Level:",
              choices = region.names, selected = region.names[1]),
  #select data type to predict: visits or any flutype
  selectInput(inputId = "data.type", label = "Select Data",
              choices = datatype, selected = datatype[1]),

  #select weeks to predict ahead
  numericInput(inputId = "Pred.Length", 
               label = "Number of weeks to predict:", min = 4, max = 104, 
               value = 52, step = 13),
  #select length of original data
  numericInput(inputId = "Orig.Length",
               label = "Number of previous weeks`:", min = 1, max = 445,
               value = 100, step = 5),
  
  helpText("Loading model, will take more than 10 seconds, sorry for waiting...")
)

renderPrint({
  #national level
  if(input$Region=="national"){
    if(input$data.type %in% c(datatype[1], age.groups)){
      if(input$data.type == datatype[1]){
        series <- visits.national[,X..WEIGHTED.ILI] #ILI total rates
      }
      else{
        series <- visits.national[,get(input$data.type)] #ILI by age group
      }
    }
    else{
        series <- flutype.national[,get(input$data.type)] #flu type
    }
  }
  else{
    #state level
    if(input$data.type == datatype[1]){
      series <- visits.state[REGION==input$Region, 
                             na.omit(as.numeric(ILITOTAL)/as.numeric(`TOTAL PATIENTS`))]
      #visits
    }
    else{
      if(input$data.type %in% age.groups){
        series = NULL #no data for state level ILI visits by age groups
      }
      else{
        series = flutype.state[REGION==input$Region,get(input$data.type)] #flu type
      }
    }
  }
  
  if(length(series)<10){
    print("Sorry, the data size is too small to construct models. Please change the Region to National level.")
  }
  else{
    #fitting arima model
    m.auto <- auto.arima(series, max.p = 3) 
    arma <- m.auto$arma #subtracts the orders of SARIMA model
    
    result <- list(`model order` = c(p=arma[1], d=arma[6], q=arma[2],
                                     P=arma[3], D=arma[7], Q=arma[4]),
                   coefficients = data.table(term = names(m.auto$coef),
                                             coefficients = m.auto$coef,
                                             variance = diag(m.auto$var.coef)),
                   criteria = c(AICC = m.auto$aicc, AIC = m.auto$aic,
                                BIC = m.auto$bic)
                   )
    result
  }
})

renderPlot({
  #national level
  {if(input$Region=="national"){
    if(input$data.type %in% c(datatype[1], age.groups)){
      if(input$data.type == datatype[1]){
        series <- visits.national[,X..WEIGHTED.ILI] #ILI total rates
      }
      else{
        series <- visits.national[,get(input$data.type)] #ILI by age group
      }
    }
    else{
      series <- flutype.national[,get(input$data.type)] #flu type
    }
  }
  else{
    #state level
    if(input$data.type == datatype[1]){
      series <- visits.state[REGION==input$Region, 
                             na.omit(as.numeric(ILITOTAL)/as.numeric(`TOTAL PATIENTS`))] 
      #visits
    }
    else{
      if(input$data.type %in% age.groups){
        series = rep(0,2) #no data for state level ILI visits by age groups
      }
      else{
        series = flutype.state[REGION==input$Region,get(input$data.type)] #flu type
      }
    }
  }}
  {  
  if(length(series)<10){
    ggplot(data = data.table(week=1:length(series), number=as.numeric(series)),
           aes(x = week, y = number))+
      geom_line(size=2)+
      labs(title = "Data size too small to contruct a model. Please change the region to nation level, or change the data type to 'Visit Rates for ILI'")+
      theme(plot.title = element_text(hjust = 0.5))
  }
  else{
    series <- ts(series, frequency = 52)
    
    #fitting arima model
    m.auto <- auto.arima(series, max.p=3, trace=T) 
    
    #forecast
    pred.list <- forecast(m.auto, h = input$Pred.Length) #point forecasts and CIs
    predictions <- pred.list$mean

    #plot forecast
    orig <- data.table(week = 1:input$Orig.Length,
                       data = series[-1:(-(length(series)-input$Orig.Length))])
    pred <- data.table(week = (input$Orig.Length+1):(input$Orig.Length+
                                                       length(predictions)),
                       data = c(predictions))
    
    ggplot(data = orig, aes(x=week, y=data))+
      geom_line(size = 2, col = "dodgerblue")+
      geom_smooth(data = pred, aes(x=week, y=data, ymax=pred.list$upper[,2],
                                   ymin=pred.list$lower[,2]),
                  col = "LightCoral", size = 2, stat="identity")+
      geom_vline(xintercept = input$Orig.Length,linetype=4,col="brown")+
      geom_text(data = data.frame(week = input$Orig.Length, 
                                  event = "March 2019(12th week)"),
                aes(x = week, y=0, label = event),
                size = 5, col = "Black", angle = 0, vjust=1.3, hjust=.5)+
      labs(title = "Original data with Predictions")+
      theme(plot.title = element_text(hjust = 0.5))
  }}
})
```