---
title: "map"
output: flexdashboard::flex_dashboard
runtime: shiny
---


```{r setup, include=FALSE}
library(highcharter)
library(dplyr)
library(viridisLite)
library(forecast)
library(treemap)
library(flexdashboard)
library(readxl)
library(readr)
library(arules)

library(shiny)
library(rmarkdown)
library(knitr)
library(Hmisc)
library(DT)

thm <- 
  hc_theme(
    colors = c("#1a6ecc", "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Source Sans Pro")
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  )

```


```{r read_data, include=FALSE}
ILINet_state <- read_csv("~/Desktop/Columbia/Spring 2019/applied data science/final project/machine-churning/ILINet-state.csv")
ILINet_state$ILITOTAL<-as.numeric(ILINet_state$ILITOTAL)
ILINet_state$`TOTAL PATIENTS`<-as.numeric(ILINet_state$`TOTAL PATIENTS`)
ILINet_state$totalp<-ILINet_state$`TOTAL PATIENTS`

#ILINet_state$month<-lubridate::month(as.Date(paste0(ILINet_state$YEAR, "-", ILINet_state$WEEK, "-", 10), format = "%Y-%U-%u"))

#ILINet_state$date<-paste(ILINet_state$YEAR,ILINet_state$month,1,sep="-")
#ILINet_state$date<-as.Date(ILINet_state$date,"%Y-%m-%d")


ili3<-ILINet_state%>%
  group_by(REGION,YEAR) %>%
  summarise(sumili=sum(ILITOTAL),
            sumTotal=sum(totalp)) 

ili4<-ili3 %>%
  group_by(REGION,YEAR) %>%
  summarise(percent=round(100*sumili/sumTotal,2))


aggts<-ts(ili4$percent,start=2010,freq=1)

usgeo<-data("usgeojson")

n <- 4
colstops <- data.frame(
  q = 0:n/n,
  c = substring(viridis(n + 1), 0, 7)) %>%
  list_parse2()
#aggts %>% 
#  forecast(level = 95) %>% 
#  hchart() %>% 
#  hc_add_theme(thm)%>%
 # hc_yAxis(max = 10,
 #          min=0)
```



Map
===================================


Row {data-height=800}
-------------------------------------

```{r respondents}
inputPanel(
  selectInput(inputId = "year", label = "Year",  choices = seq(2010,2019,by=1), 
              selected = 2010)
)

renderPlot({
  
  n <- 4
colstops <- data.frame(
  q = 0:n/n,
  c = substring(viridis(n + 1), 0, 7)) %>%
  list_parse2()


highchart() %>%
  hc_add_series_map(usgeojson, ili4[ili4$YEAR==input$year, ], name = "Percentage",
                    value = "percent", joinBy = c("woename", "REGION"),
                    dataLabels = list(enabled = TRUE,
                                      format = '{point.properties.postalcode}')) %>%
  hc_colorAxis(stops = colstops) %>%
  hc_legend(valueDecimals = 0, valueSuffix = "%") %>%
  hc_mapNavigation(enabled = TRUE) %>%
  hc_add_theme(thm)

})
```


